[Sky] TodoList with Ajax -
next-step/js-todo-list-step2 pull request #15
Opened 2020-08-23 00:57 UTC by SkynI25

## 🎯 요구사항
- [x] todoItem 불러오기
- [x] todoItem 추가하기
- [x] todoItem 삭제하기
- [x] todoItem complete하기
- [x] todoItem contents 내용 수정하기
- [x] user별 투두리스트 불러오기

## 🎯🎯 심화 요구사항
- [x] 데이터를 불러오기전 로딩바를 이용해, 사용자가 데이터가 불러와지고 있다는 것을 보여줍니다.
- [x] github issue에서 라벨을 붙이는 것처럼, 우선순위에 따라서 badge를 추가합니다.

## <del>현재 막힌 부분</del>
- <del>클릭에 따라 Filter 가 제대로 바뀌지 않음, hash 값과 연관 있는 것으로 보임</del>(해결)

## 진행하면서 배운 부분
- ``객체지향의 사실과 오해`` 라는 책을 겸전하면서 진행을 하다보니, 객체 지향적으로 짜게 되었을때의 효과를 몸소 느끼는 것 같습니다.
- @ganeodolu 과의 페어프로그래밍을 진행하면서 api를 보다 깔끔하게 정리하여 사용하는 방법을 익힐 수 있었습니다 👍 
- 수연님의 PR을 읽으며 각 컴포넌트에 해당하는 마크업 부분을 htmlTemplate 모듈화하는게 코드를 깔끔하게 짤 수 있겠다라고 배울 수 있었습니다 👍 (이것이 코드리뷰의 묘미..!)

## 참고자료
- https://github.com/next-step/js-todo-list-step2/pull/2#pullrequestreview-438166309
- https://developer.mozilla.org/ko/docs/Web/API/Node/nextSibling
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

2020-08-23 10:12 UTC, ganeodolu commented on components/TodoList.js
> +      evt.target.tagName === "INPUT" &&
target의 특성을 찾을 때 tagName을 주로 사용하시는데 저는 클래스명이 특성을 잘 나타낸다고 알고있어서요.
예를 들어 버튼태그가 여러개일 경우? 혹시 제가 잘못 알고 있을 수 있고, 다른 의견이 궁금해서 남겨봅니다 :frog:

2020-08-23 13:35 UTC, SkynI25 commented on components/TodoList.js
> +      evt.target.tagName === "INPUT" &&
아 그렇군요, @ganeodolu 님께서 말씀하신대로 클래스를 사용하면 더 해당 엘리먼트에 근접하게 접근할 수 있는 것 같습니다 :) 저의 경우 경험상 델리게이션을 사용해서 자식 엘리먼트를 지정할 때 tagName 을 사용하면 제대로 엘리먼트를 지정하는 것으로 기억해서 ``페어프로그래밍`` 당시 그렇게 말씀드렸습니다. tagName 을 이용한 비교와 className을 이용한 비교에 대해서 고민해보겠습니다. 짚어주셔서 감사드립니다 :) 👍

2020-08-24 13:10 UTC, wooooooood commented on utils/data.js
> +    id: `${createUniqueID()}0`,
샘플데이터를 만드신 부분인가요? `createUniqueID`를 사용하신 점이 인상깊습니다 👍

2020-08-24 13:17 UTC, wooooooood commented on components/TodoList.js
> +      evt.target.closest("li").childNodes[3].focus();
3은 매직넘버인가요? 👀 상수로 분리하시면 더 이해하기 쉽지 않을까 의견 남겨봅니당~~

2020-08-24 13:20 UTC, wooooooood commented on components/TodoError.js
> +  this.state = {
와우 에러를 따로 분리하시다니.. 생각도 못했떤 부분입니다 👍

2020-08-25 09:46 UTC, 2SOOY commented on components/App.js
> +  }
안녕하세요:) @SkynI25님!

이 부분에서 throw한 error를 `catch하는 부분`이 없는 것 같습니다 :)

2020-08-25 09:46 UTC, 2SOOY commented on components/App.js
> +  urlHrefClear();
혹시 `urlHrefClear`는 어떤 동작을 위해 사용한 함수인지 설명해주실 수 있나요 ?

2020-08-25 09:46 UTC, 2SOOY commented on components/App.js
> +  }) => {
이 부분은 
`this.setStateForRendering = ({ todoList, todoCount, todoFilter }) => { ... }`
이렇게 쓸 수 있을 것 같아요 !

2020-08-25 09:46 UTC, 2SOOY commented on components/App.js
> +  this.setState = (todoList) => {
이건 제 생각인데요,

`line 193` 
state를 변경하는 부분에서는 `setUser`라고 네이밍 해주셨는데,

`line 197` 
해당 메소드의 body를 보면 todoList와 todoCounts의 state를 변경하시는데,
따라서 `setState` 대신 `setTodos`와 같은 네이밍이 더 직관적일 것  같아요 😄 
(아마 `setState`라고 지으신 이유가 해당 메소드 안에서 `render()`를 진행하기 때문인것 같군요 !)

2020-08-25 09:46 UTC, 2SOOY commented on components/TodoError.js
> +  this.state = {
ERROR에 대한 UI처리도 하셨군요 ! 👍

2020-08-25 09:46 UTC, 2SOOY commented on components/App.js
> +  } catch {}
catch 에 대한 처리가 비워져있습니다 :)

2020-08-25 15:47 UTC, SkynI25 commented on utils/data.js
> +    id: `${createUniqueID()}0`,
넵 맞습니다 :) 그렇게 말씀해주시니 더욱 열의가 생기는군요! 감사합니다  :)

2020-08-25 15:48 UTC, SkynI25 commented on components/TodoList.js
> +      evt.target.closest("li").childNodes[3].focus();
감사합니다 ㅎㅎㅎ 말씀하신대로 3은 li 태그 내의 자식 요소 중 label 태그를 가리키는 것인데, 이를 숫자로 나타내는 것이 마음에 석연찮았습니다. 말씀해주신대로 고친다면 코드가 더욱 깔끔해질거 같네요!! 👍

2020-08-25 15:49 UTC, SkynI25 commented on components/App.js
> +  }
앗..맞네요..수연님의 정확한 지적 감사드립니다 :)

2020-08-25 15:54 UTC, SkynI25 commented on components/App.js
> +  urlHrefClear();
urlHrefClear 함수는 페이지 새로고침시에 hash를 초기화하는 용도로 생성하였습니다, 예를 들어 active 필터를 클릭하면 url은 ``http://127.0.0.1/index.html#/actvie`` 과 같이 hash가 생기게 됩니다. 이것이 새로고침 뒤에도 남아있게 되어 현재 필터 표시에 영향을 준다고 생각했습니다 :)

2020-08-25 15:54 UTC, SkynI25 commented on components/App.js
> +  }) => {
감사합니다, 좋은 지적 입니다 :)

2020-08-25 16:53 UTC, SkynI25 commented on components/App.js
> +  this.setState = (todoList) => {
수연님 정확히 짚어주셔서 감사드립니다 :) 말씀하신대로 해당 부분에서 어떻게 처리를 해줘야할지 고민이 되고 있었습니다..모든 객체는 상태를 가지고 행동을 통해서 상태를 변경하게끔 하고 싶었습니다. 그리고 이에 대해서 setState 라는 메서드로 통일을 하여 처리를 하고 싶었는데, 초기에 유저를 세팅하는 것과 유저리스트를 클릭해서 유저를 변경한뒤 todoList를 세팅하는 부분을 처리하다보니 해당 부분에서 setUser, setState 와 같은 이름의 메서드로 된거 같습니다. 말씀하신대로 setTodos가 더 직관적인 네이밍일 것 같습니다. 피드백 감사드립니다!! 👍

2020-08-25 16:54 UTC, SkynI25 commented on components/App.js
> +  } catch {}
아아, 그렇네요 피드백주셔서 감사합니다 :)

2020-08-26 00:28 UTC, EastjunDev requested changes
sky님 코드 보면서 꼼꼼한 validation 체크 및 로그 처리에 감탄하였습니다 ㅎㅎ
저뿐만 아니라 다른 분들에게도 학습할 좋은 코드 공유해주셔서 너무 감사드립니다.
몇가지 간단한 피드백 드렸으니 참고 부탁드릴게요 😄

2020-08-26 00:28 UTC, eastjun-dev commented on .prettierrc
> +{
.prettierrc 👍👍👍

2020-08-26 00:28 UTC, eastjun-dev commented on components/App.js
> +      validateTodoList(todos) ? this.setState(todos) : null;
삼항연산자에서 false의 경우 아무런 로직을 넣지 않는다면
`validateTodoList(todos) && this.setState(todos);`
위와 같이 간단하게 작성하실 수 있습니다 😄

2020-08-26 00:28 UTC, eastjun-dev commented on components/App.js
> +      const todos = [...this.state.todoList, todo];
원본 객체의 상태를 건드리지 않으면서 작성하시는 습관이 있으시군요 👍 👍 👍 👍 👍

2020-08-26 00:28 UTC, eastjun-dev commented on components/TodoError.js
> +  this.state = {
크.... 멋집니다 👍

2020-08-26 00:28 UTC, EastjunDev commented on components/TodoFilter.js
> +      evt.target.tagName === "A" &&
`tagName`과 `class`까지 같이 비교하는 꼼꼼함!!!!! 👍

2020-08-26 00:28 UTC, EastjunDev commented on components/TodoFilter.js
> +        el.tagName === "LI" ? el.childNodes[1].hash.split("/")[1] : NOTLI;
`NOT LI`를 표현하시려는 거면 `NOT_LI`이렇게 하는게 더 가독성이 좋을 것 같아요 ㅎㅎ

2020-08-26 00:28 UTC, EastjunDev commented on components/TodoList.js
> +      evt.target.tagName === "INPUT" &&
`tagName`을 이용하면, ui의 변화같은 일로 인해 마크업이 변경된 경우, 에러가 발생할 수 있을 것 같아요. 그래서 저의 경우에도 항상 className을 이용해 비교합니다 ㅎㅎ 참고 부탁드릴게요 😉

2020-08-26 00:28 UTC, EastjunDev commented on utils/api.js
> +  getUserListFromAPI: () => {
`FromApi`란 이름이 중복되서 계속 네이밍에 사용이 되고 있는 것 같다는 생각이 들어요. api객체 안에 있는 메서드들이기 때문에 자연스럽게 fromApi란 의미가 내포되었을 것 같은데, 네이밍에 추가로 적어주신 이유가 있으실까요? 🤔

2020-08-26 00:28 UTC, EastjunDev commented on utils/util.js
> +  return false;
```javascript
return  user.hasOwnProperty("name") &&
    user.hasOwnProperty("_id") &&
    user.name.length > 0 &&
    typeof user.name === "string" &&
    typeof user._id === "string"
```
이렇게만 작성해주셔도 동일한 의미의 코드가 될 것 같아요 😄

2020-08-26 00:28 UTC, EastjunDev commented on utils/util.js
> +}
```javascript
return todoList.every(
      (todo) =>
        todo.hasOwnProperty("_id") &&
        todo.hasOwnProperty("contents") &&
        todo.hasOwnProperty("isCompleted") &&
        todo.hasOwnProperty("priority") &&
        todo._id.length > 0 &&
        todo.contents.length > 0 &&
        typeof todo.contents === "string" &&
        typeof todo._id === "string" &&
        typeof todo.isCompleted === "boolean"
```

이렇게만 작성해주셔도 동일한 의미의 코드가 될 것 같습니다 😄

2020-08-26 00:28 UTC, EastjunDev commented on utils/template.js
> +        _id === currentUserId ? ACTIVE : ""
`_id === currentUserId && ACTIVE`
이렇게 작성하시면 더 깔끔해질 것 같아요 😄

2020-08-27 07:46 UTC, 2SOOY commented on components/App.js
> +  urlHrefClear();
답변 감사합니다! 이해했어요 👍 
탭 선택시 url에 hash가 붙기 때문에, 새로고침 동작에서도 신경을 써줘야 했군요 :)

2020-08-28 17:27 UTC, lsw1164 reviewed
element의 Id를 비롯해서 전반적인 상수값들을 따로 관리하신게 인상깊었습니다 👍

2020-08-31 08:37 UTC, SkynI25 commented on utils/api.js
> +  getUserListFromAPI: () => {
동준님 피드백 감사드립니다 :) 이 부분은 제가 네이밍에 대한 큰 고려없이 짜다보니 나타난 문제로 보여집니다. API로 부터 TodoList를 받아올건데, 이를 내포할 수 있는 의미가 무엇이 있을까 고민을 했는데 좀 더 깊이있게 생각해야 코드를 읽을 때 혼동을 줄일 수 있게 될 것 같네요!! 감사합니다 :)

2020-09-01 06:57 UTC, read0more reviewed
@SkynI25 님 코드 잘봤습니다~! 에러에 대해 따로 처리하신 부분은 생각도 못했는데 보면서 많이 배워갑니다 ㅎㅎ 이미 다른 분들이 좋은 피드백 많이 남겨주시기도 했고 우선 제가 발견한 버그만 코멘트로 남겼습니다😄

2020-09-01 06:57 UTC, read0more commented on utils/util.js
> +  return todoList.every(
todo가 없는 유저를 클릭 할 시에 todoList가 undefined라서 에러가 나는 것 같습니다~

2020-09-08 10:49 UTC, closed without merging