[4기 박병길] TodoList with Ajax
next-step/js-todo-list-step2 pull request #27
Opened 2020-11-03 15:21 UTC by bgpark82

필수 미션을 완료하였지만 아직 미진한 부분이 남아있습니다. 
고민 중인 부분이 아직 있어 빠르게 피드백을 받으면서 계속 이어나갈 계획입니다.
하단에서 고민하고 있는 부분들을 적어놓았는데 피드백 해주시면 감사하겠습니다.

## 🎯 요구사항

-   [x] 1. User 추가하기
-   [x] 2. User의 투두리스트 불러오기
-   [x] 3. User 삭제하기
-   [x] 3. todoItem 추가하기
-   [x] 4. todoItem 불러오기
-   [x] 5. todoItem complete하기
-   [x] 6. todoItem 삭제하기
-   [x] 7. todoItem contents 내용 수정하기

## 🎯🎯 심화 요구사항

-   [ ] 1. 데이터를 불러오기전 로딩바를 이용해, 사용자가 데이터가 불러와지고 있다는 것을 보여줍니다.
-   [x] 2. fetch api 사용하는 부분을 async await을 사용하여 리팩토링합니다.
-   [ ] 3. github issue에서 라벨을 붙이는 것처럼, 우선순위에 따라서 badge를 추가합니다.
-   [x] 4. ES6 impot & export를 이용해 자바스크립트 파일을 리팩토링합니다.

## 🕵️‍♂️ 제약사항

-   [x] 1. User의 이름은 최소 2글자 이상이어야 합니다.

## 고민

-   [ ] 1. API 처리속도가 느려서 상태 업데이트 후, UI 반영이 늦은 경우
-   [ ] 2. Store를 각 Component에서 분리하는 방법

2020-11-04 16:18 UTC, eyabc commented
`API 처리속도가 느려서 상태 업데이트 후, UI 반영이 늦은 경우`  이 이유 때문에 
심화미션 `1. 데이터를 불러오기전 로딩바를 이용해, 사용자가 데이터가 불러와지고 있다는 것을 보여줍니다` 을 구현하는 것으로 알고있습니다!

2020-11-04 16:33 UTC, eyabc reviewed
안녕하세요 병길님! 코드가 정말 말끔해서 가독성도 정말 좋았습니다. 
코드 보면서 많이 배웠고! 특히 API 와 STORE 부분이  인상깊어서  꼭 활용해 보고싶네요!

2020-11-04 16:33 UTC, eyabc commented on js/api/todoApi.js
> +import Api from "../utils/api.js";
체이닝 부분이 너무 깔끔하고 인상적입니다! 다음 미션에서 병길님이 쓰신 방법 꼭 써보고 싶네요!

2020-11-08 08:12 UTC, knae11 reviewed
제가 모듈로 나누는 게 아직 많이 어려운데 병길님 코드 보면서 많이 방안에 대해 생각해 본 것 같아요!ㅎㅎㅎ  template이나 constant로 셋팅해 놓고 사용하는 방식과  메서드를 구성하는 방식이 이해하기 잘 되어있는 것 같아 많이 배웠습니다! 😊

2020-11-08 08:12 UTC, knae11 commented on js/api/todoApi.js
> +import Api from "../utils/api.js";
새롭게 상태변화가 일어날 때마다, api를 계속 불러와서 불편했는데 아래처럼 함수로 만들어서 체이닝을 걸어 놓으면 편하군요!! 👍👍

2020-11-08 08:12 UTC, knae11 commented on js/api/todoApi.js
> +import Api from "../utils/api.js";
아래 메서드들을 다른파일에서 한 번에 import 하여 사용하는 것 같아서요..! class로 묶어서 export하지 않고 각각 export하는 이유가 있을까요...??

2020-11-08 08:12 UTC, knae11 commented on js/components/TodoList.js
> +    this.bindEvents = () => {
오~이렇게 같이 쓰이는 이벤트끼리 묶어주는 방법도 있군요!!👍

2020-11-18 10:24 UTC, imakerjun requested changes
와 병길님의 코드를 보는데 깔끔한 api 객체 분리와, 상태 관리를 위한 역할 분리가 너무나 인상적이에요! 
저뿐만 아니라 다른 분들도 병길님 코드를 보시면서 많은 인사이트를 얻어갈 수 있을 것 같습니다!
몇가지 참고해주셨으면 하는 피드백 남겨드렸는데 확인 부탁드릴게요 😄

2020-11-18 10:24 UTC, imakerjun commented on .vscode/settings.json
> +}
IDE관련 파일의 경우 `.gitignore`에 추가하여 따로 원격저장소에는 push하지 않도록 해주시면 좋습니다 😄

2020-11-18 10:24 UTC, imakerjun commented on js/components/App.js
> +            payload: await addUser(username),
만약에 `addUser` 통신이 실패한 경우에 로직 처리는 어떻게 될까요? 🤔 
모든 비동기통신은 success or fail의 경우를 같이 고려해야, 더 안정적인 만들 수 있을 것 같아요 😄 
[링크](https://rinae.dev/posts/how-to-handle-errors-1)를 참고하시면 도움이 될 것 같습니다!

2020-11-18 10:24 UTC, imakerjun commented on js/components/TodoList.js
> +        if (e.target.className === CLASS.TOGGLE) {
`className`을 다룰때는 [classList](https://developer.mozilla.org/ko/docs/Web/API/Element/classList)에 있는 메서드를 사용하시는게 좋습니다. className은 class들을 하나의 string으로 return 해주므로, 나중에 스타일 추가를 위해 class가 추가된 경우 에러를 발생시킬 수 있습니다 😭

2020-11-18 10:24 UTC, imakerjun commented on js/components/TodoList.js
> +        }, "");
`return todos.reduce((html, todo) => html += todoDom(todo), "")` 이렇게 한줄로 표현하는 것도 가능할 것 같아요 😄

2020-11-18 10:24 UTC, imakerjun commented on js/components/UserList.js
> +        }
개인적으로 if문이 중첩으로 있으면, 놓치는 예외사항을 체크하지 못하는 경우들이 종종 있어, 이렇게 depth를 최소화해보시면, 다른 예외조건을 추가할 때도 훨씬 경우의수가 명확해질 수 있을 것 같아요 😄 
```javascript
if (!isUserCreate(e)) {
   return
}

const username = prompt(MESSAGE.INPUT_USERNAME);

if (!username) return;

if (!isValidUsername(username)) {
    throw new Error(MESSAGE.INVALID_USERNAME);
}

onAddUser(username);
```

2020-11-18 10:24 UTC, imakerjun commented on js/index.js
> +document.addEventListener(EVENT.DOM_LOADED, async () => {
`index.js`파일 자체를 dom이 로드된다음에 불러오는데 `EVENT.DOM.LOADED` 이벤트에 바인딩하신 이유가 혹시 있을까요? 🤔

2020-11-18 10:24 UTC, imakerjun commented on js/utils/templates.js
> +    </li>`;
template을 따로 분리하여 한곳에서 보기 쉽게 만들어주셨군요 👍🏻

2020-11-18 10:24 UTC, imakerjun commented on js/utils/validator.js
> +    if(!$target instanceof HTMLElement) {
다른 곳에서는 If 다음에 공백이 있는데, 여기서는 붙여서 쓰신것 같아요. 통일 시켜주시면 더 가독성 좋은 코드가 될 것 같아요 😄

2020-12-09 01:20 UTC, merged

2020-12-10 04:51 UTC, alonez89 commented
너의 근황이 궁금했는데 즐기면서 개발하는구나...