[5기 김우정] TodoList with Ajax
next-step/js-todo-list-step2 pull request #37
Opened 2020-12-12 15:43 UTC by wj2kim

안녕하세요. 5기 김우정입니다.

2주차 미션 올립니다 :)

> **🎯 요구사항**
> 
> * [x]  1. User 추가하기
> * [x]  2. User의 투두리스트 불러오기
> * [x]  3. User 삭제하기
> * [x]   3. todoItem 추가하기
> * [x]  4. todoItem 불러오기
> * [x]  5. todoItem complete하기
> * [x]  6. todoItem 삭제하기
> * [x]  7. todoItem contents 내용 수정하기
> 
> **🎯🎯 심화 요구사항**
> 
> * [x]   1. 데이터를 불러오기전 로딩바를 이용해, 사용자가 데이터가 불러와지고 있다는 것을 보여줍니다.
> * [x]    2. fetch api 사용하는 부분을 async await을 사용하여 리팩토링합니다.
> * [x]  3. github issue에서 라벨을 붙이는 것처럼, 우선순위에 따라서 badge를 추가합니다.
> * [x]  4. ES6 impot & export를 이용해 자바스크립트 파일을 리팩토링합니다.
> 
> **🕵️‍♂️ 제약사항**
> 
> * [x]   1. User의 이름은 최소 2글자 이상이어야 합니다.

2020-12-15 07:27 UTC, hwookim requested changes
안녕하세요 우정님!
리뷰 같은 조가 된 WOO입니다!😄

컴포넌트 별로 분리해서 깔끔하게 코드를 짜주셨네요! 👍

저는 에러 처리에 대해서 신경을 안쓰고 코드를 짰는데...
세심하게 에러까지 처리해주신 점은 저도 배워야겠네요.👀

몇가지 리뷰 남겼으니 확인 부탁드려요!
많이 배워갑니다.👍 👍

2020-12-15 07:27 UTC, hwookim commented on js/components/UserList.js
> +        console.log(this.users, this.activeUser);
확인용으로 사용하셨던 console.log는 제거하면 좋을 것 같아요!😄

2020-12-15 07:27 UTC, hwookim commented on js/components/UserList.js
> +            console.log("err", err);
```suggestion
            console.error("err", err);
```
에러임을 좀 더 명확하게 표시하기 위해 단순 로그보단 `error`를 사용해보는 건 어떨까요?

2020-12-15 07:27 UTC, hwookim commented on js/components/UserList.js
> +    this.initialIdForTest = 'woSRmp5oh';
초기 아이디를 지정한 유저가 없을 수도 있지 않을까요?
직접 지정하기 보다는 서버에서 응답으로 내려준 전체 유저 중 하나를 고르는 건 어떤가요?😄

2020-12-15 07:27 UTC, hwookim commented on js/components/TodoApp.js
> +        this.userInfo = userInfo ?? {};
몰랐던 연산자인데 새롭게 배우네요!👀
공부할 게 많은 것 같습니다....

2020-12-15 07:27 UTC, hwookim commented on js/components/TodoApp.js
> +        )
함수를 클래스의 인자로 넘기는데다 내부에서 try-catch까지 하면서 가독성이 많이 떨어지네요.🤔
함수를 따로 분리하고 인자로만 넘길 수는 없을까요?

2020-12-15 07:27 UTC, hwookim commented on js/components/TodoApp.js
> +        }
`todos ?? []`에서 `todos`가 `null`이나 `undefined`일 경우에는 []를 반환하게 되는 것으로 이해했는데요.
그렇다면 `if(todos)`가 의미가 있나요??

제가 잘못 이해했다면 지적 부탁드려요!😄

2020-12-15 07:27 UTC, hwookim commented on js/components/TodoApp.js
> +            const todoList = await getTodoListByUserId(this.userInfo._id);
네이밍이 같아서 어떤 함수를 호출한 것인지 헷갈릴 수 있겠네요.
todoAPI에서 하나의 객체를 통해 접근할 수 있도록 감싸보는 건 어떨까요?

2020-12-15 07:27 UTC, hwookim commented on js/api/settings.js
> +    return response.text().then(text => {
`response.text()`도 몰랐던 함수네요.👀
많이 배워갑니다...😄

다만 settings라는 파일명보다는 좀 더 명확하게 API같은 네이밍은 어떨까요?

2020-12-15 07:27 UTC, hwookim commented on js/components/TodoList.js
> +    const onClickTodo = ({target}) => {
등록할 이벤트에 따라서 메소드를 구분하고 네이밍을 해주셨네요.
이벤트보다는 메소드 내에서 진행되는 `행동`을 기반으로 구분하고 네이밍하는 건 어떨까요?

이 경우에는 `toggleTodo`와 `deleteTodo`로 나누고 `addEventListner`를 두 번 사용해 두가지 이벤트를 등록할 수 있을 것 같네요.

2020-12-15 07:27 UTC, hwookim commented on js/components/TodoList.js
> +                        : todoLabelComponent(todo)
`todoLabelComponent `의 모든 경우 마지막에 `todoContentsComponent`가 들어가는데요.
중복되는 부분인 만큼 외부로 추출하는 건 어떨까요?

2020-12-15 11:40 UTC, wj2kim commented on js/components/UserList.js
> +        console.log(this.users, this.activeUser);
앗 :) 감사합니다.

2020-12-15 11:42 UTC, wj2kim commented on js/components/UserList.js
> +            console.log("err", err);
평소 로그에 에러를 사용해보지 않아서 생각을 못했었는데 다음부터 한번 사용해보도록 하겠습니다 :)

2020-12-15 11:43 UTC, wj2kim commented on js/components/UserList.js
> +            console.log("err", err);
오 평소 잘 쓰지 않아 생각을 못했네요 ㅜ. 언급해주셔서 감사합니다.

2020-12-15 11:44 UTC, wj2kim commented on js/components/UserList.js
> +    this.initialIdForTest = 'woSRmp5oh';
동감합니다. 수정해 보도록 하겠습니다 :)

2020-12-15 11:44 UTC, wj2kim commented on js/components/UserList.js
> +    this.initialIdForTest = 'woSRmp5oh';
공감합니다. 수정해보도록 하겠습니다 :)

2020-12-15 11:45 UTC, wj2kim commented on js/components/TodoApp.js
> +        this.userInfo = userInfo ?? {};
저도 이 기회에 처음 써보는 연산자입니다 :)
맞습니다. 공부 할게 산더미네요 :(

2020-12-15 11:47 UTC, wj2kim commented on js/components/TodoApp.js
> +        }
지적 감사합니다! 저도 그렇게 이해했습니다. 다시 보니 if(todos) 확인 절차는 불필요한 로직인것 같네요! 감사합니다.

2020-12-15 11:48 UTC, wj2kim commented on js/components/TodoApp.js
> +            const todoList = await getTodoListByUserId(this.userInfo._id);
저도 그 부분이 걸리긴 했습니다.. 좋은 방법을 고민해보겠습니다. :)

2020-12-15 11:50 UTC, wj2kim commented on js/api/settings.js
> +    return response.text().then(text => {
다시 보니 settings 라는 네이밍은 너무 광범위하네요. 지적 감사합니다. 좋은 네이밍을 고민해보겠습니다. :)

2020-12-15 11:51 UTC, wj2kim commented on js/components/TodoList.js
> +    const onClickTodo = ({target}) => {
공감했습니다. 수정해보도록 하겠습니다 :)

2020-12-15 12:02 UTC, wj2kim commented on js/components/TodoApp.js
> +        )
가독성 ㅜ 고민해야할 부분이네요.. 함수로 따로 분리해보는 방법을 고민해봐야겠네요! 지적 감사합니다!

2020-12-20 14:30 UTC, YUJO42 reviewed
지난 주에 말씀하신 드래그 앤 드롭으로 삭제를 구현하신게 정말 인상 깊네요! 코드 잘 봤습니다!! 

널 병합 연산자의 사용법이나 ```DataTransfer``` 속성 같은 것들도 새롭게 배워가네요! 

고생하셨습니다!!👍👍👍👍

2020-12-20 14:30 UTC, yujo11 commented on js/App.js
> +            this.state.userInfo = userInfo ?? {};
아하 널 병합 연산자를 이런식으로 사용하는거군요! 좋은거 하나 배워갑니다!

2020-12-20 14:30 UTC, yujo11 commented on js/api/todoAPI.js
> +    await delay(500)
제가 아직 미션을 진행하지 않아서 그런데 혹시 이렇게 ```delay()```를 걸어놓으신게 로딩바 보여주는 부분 때문인건가요?

2020-12-20 14:30 UTC, YUJO42 commented on js/components/UserList.js
> +            e.dataTransfer.effectAllowed = 'move';
와 이런 메소드도 존재하는군요ㅎㅎ 정말 이걸 통해서 구현하시다니 정말 멋지네요! 하나 또 배워갑니다!!👍👍

2020-12-21 00:56 UTC, wj2kim commented on js/api/todoAPI.js
> +    await delay(500)
네 맞습니다. 로딩처리 부분을 더 길게 볼 수 있게 지연시켰습니다!

2020-12-21 00:56 UTC, wj2kim commented on js/components/UserList.js
> +            e.dataTransfer.effectAllowed = 'move';
감사합니다 :)

2020-12-27 13:47 UTC, Minsiki commented on js/App.js
> +            this.state.loading = loading ?? false;
?? 이런 연산을 취했을 때는 어떤 결과가 나오는건가요?? 3항연산이랑 형태는 비슷해 보이는데 처음 보는 연산이네요.

2021-02-02 07:09 UTC, merged